### ISSUE TITLE
Near perfect Creatures 2 performance, except for the Eye window

### ISSUE THREAD

**Issue by MoogieOuttaMyDepth** [elishacloud/dxwrapper#106]
Firstly, I wanted to congratulate and thank you for providing a fix for Creatures 2! At long last, the prophecy has been fulfilled. Seriously, major kudos. It has been a long struggle getting this game to play nicely on modern Windows.

It runs so well with the fixes you posted, but there is one remaining issue, which is best described with a screenshot:

![image](https://user-images.githubusercontent.com/8050477/102073441-37f7bb80-3dfb-11eb-9eae-b28018f3a99e.png)

When not on top of the game window, it doesn't render at all:

![image](https://user-images.githubusercontent.com/8050477/102073638-83aa6500-3dfb-11eb-8805-33df512f06a7.png)

It almost seems too much to hope for, but maybe there is just one more small tweak needed to get it redrawing correctly? Then this game could almost be considered 100% compatible!

**Comment by elishacloud** [comment]
The trouble here is that I am rendering everything to the main window.  So when another render window appears on top the contents of that window is also displayed to the main window.  Then when you move it outside the main window it can no longer render it.

The proper fix would be to render to the correct window.  That may take a bit of time because I am not completely sure how to tell what window it is rendering to.  However, let me look into a different way of fixing this.

BTW: I found the core issue with Creatures 2 and added the fix [here](https://github.com/elishacloud/dxwrapper/blob/d7b2e94c5291e5155aadb641dde892fcc8c13555/ddraw/IDirectDrawSurfaceX.cpp#L538-L559) and [here](https://github.com/elishacloud/dxwrapper/blob/d7b2e94c5291e5155aadb641dde892fcc8c13555/ddraw/IDirectDrawSurfaceX.cpp#L650-L658).  Creatures 2 would use a rect for Blt that is 1 pixel too large and Windows would fail the Blt.  Then Creature 2 would see the error message and exit the game.  I just added code to detect this case and retry the Blt using a slightly smaller rect.

**Comment by MoogieOuttaMyDepth** [comment]
If you could read through the game's original rendersystem.cpp, display.cpp and ddraw.cpp, would that be helpful at all?

If so, is there any way to contact you privately?

**Comment by elishacloud** [comment]
Yes, having the game's source code may help here.  You can email me at elisha at novicemail.com.

Also, how do you get the Eye window to popup?

**Comment by elishacloud** [comment]
This issue should be fixed in the latest release:  https://github.com/elishacloud/dxwrapper/wiki/Creatures-2:-The-Albian-Years
