### ISSUE TITLE
Halo CE: fails to show title screen when setting antialiasing

### ISSUE THREAD

**Issue by nerevar009** [elishacloud/dxwrapper#118]
When setting antialiasing for Halo CE, the game doesn't remove the logo image that's shown before the title screen loads. The title screen still loads behind it, the music plays and the arrow keys make sounds navigating the menu, but the logo image covers the whole screen. Works fine with no antialiasing. It happens in both fullscreen and the game's windowed mode (enabled with -window command line option). 

[config file](https://github.com/elishacloud/dxwrapper/files/6254577/dxwrapper.txt)
[dxwrapper-haloce.log](https://github.com/elishacloud/dxwrapper/files/6254578/dxwrapper-haloce.log)

Windows 10 64bit, Acer Chromebook 15 CB3-532, Intel iGPU

**Comment by Squall-Leonhart** [comment]
Don't set MSAA for this game, its not supported.

> 1.3.1 Is hardware anti-aliasing supported?
> 
>    No. Halo renders everything to multiple off-screen surfaces instead of directly to the D3D back buffer and hardware anti-aliasing is applied on the back buffer only. For Halo, we have to do this because some of the effects (such as the active camouflage or the zoom scope) require the back buffer as source data.

**Comment by elishacloud** [comment]
> hardware anti-aliasing is applied on the back buffer only

This is not quite true with dxwrapper.  I actually create each render target with multi-sampling (anti-aliasing) enabled so that even if you render to another offscreen surface it will have AA enabled.

The issue here does not seem related to AA not getting enabled, but rather an issue with some surface not being able to be seen.  I am using a shadow surface along side the render targets and maybe dxwrapper is not able to copy the data to the shadow surface.  I need to investigate this more.

Can you check with the latest build?  I have done a lot of improvements to this AA support since 2021.

**Comment by Squall-Leonhart** [comment]
There is visible crawling on environment walls in multiplayer maps such as  blood gulch, felt nauseating.

AA did not appear to be working though, saw the same jaggy steps on surfaces.

**Comment by elishacloud** [comment]
> AA did not appear to be working though, saw the same jaggy steps on surfaces.

It is possible that the game renders to a texture.  There is no way to do AA on textures.

However, does the initial issue still exist?  Can you see the logo and title screen of the game?

**Comment by Squall-Leonhart** [comment]
The logo and 3D Halo all rendered as it should.

**Comment by elishacloud** [comment]
Ok, thanks for checking.  I am going to close this case as complete.
