### ISSUE TITLE
RealDllPath not working

### ISSUE THREAD

**Issue by RibShark** [elishacloud/dxwrapper#12]
I'm trying to get this working with Tonic Trouble and dgVoodoo in the following fashion:
* The stub DLL is named "ddraw.dll".
* dgVoodoo's ddraw.dll is named "dg_ddraw.dll".
* In ddwrapper.ini, RealDllPath is set to dg_ddraw.dll.

However, the ddraw.dll loaded by dxwrapper is the system's "ddraw.dll" and not the "dg_ddraw.dll" I set in the ini. The log shows that the configuration file was loaded correctly.

**Comment by RibShark** [comment]
Fixed by not using the stub and just renaming ddwrapper.dll to ddraw.dll

I think this may still be a bug though as it doesn't work when using the stub.

**Comment by elishacloud** [comment]
Yes, the `RealDllPath` won't work when dxwrapper is loaded from a stub since it is _not_ being loaded as a wrapper dll.  Instead you need to tell the stub to load the custom dll since the stub is running as the wrapper.

If ddraw.dll is the stub then you can create a `ddraw.ini` text file and add the `RealDllPath` config option to this file.  The stub should be able to read this and load the dgVoodoo dll this way.

Note: `RealDllPath` and `WrapperMode` are the only two config options supported by the stub.  When using the stub these options need to be configured in the stub and not in dxwrapper.
