### ISSUE TITLE
dgVoodoo + DxWnd + dxwrapper

### ISSUE THREAD

**Issue by RibShark** [elishacloud/dxwrapper#13]
For a game I am trying to fix (Tonic Trouble), in order for it to work perfectly I need to run it with both dgVoodoo (wrapping around ddraw.dll) and DxWnd. On top of this, I would also like to use dxwrapper for it's ability to load ASI/DLL files, which I will be using to further enhance the game. Without dxwrapper, I can use dgVoodoo and DxWnd's proxy DLL to load them both at the same time.

The problem is, when I try and use dxwrapper to load DxWnd rather than DxWnd's proxy DLL, it doesn't work with dgVoodoo and all DxWnd tweaks have no effect. If I remove dgVoodoo it does wrap it, but DxWnd alone has serious graphical issues with this game.

**Comment by elishacloud** [comment]
What version of DxWnd are you using?  dxwrapper only supports DxWnd v2.03.60 at this time.  See [here](https://github.com/elishacloud/dxwrapper/blob/master/DxWnd/v2_03_60_src/dxwnd.h) and [here](https://github.com/elishacloud/dxwrapper/blob/master/DxWnd/v2_03_60_src/init.cpp).

How are you using both dgVoodoo and DxWnd's proxy DLL?  Can you give me more details on how you have this setup?

**Comment by elishacloud** [comment]
I tested with the latest version of DxWrapper [here](https://github.com/elishacloud/dxwrapper/releases) and it works fine with DxWnd + dgVoodoo on the games I tested, when using DxWnd version 2.03.60.

Since I have not gotten any response I am closing this issue.  If you still have an issue you can reopen it.
