### ISSUE TITLE
Keep Filter If Point Sampled (AnisotropicFiltering\AntiAliasing)

### ISSUE THREAD

**Issue by Mitradis** [elishacloud/dxwrapper#144]
Need support separation filtering objects on Point and non-Point. It need becouse now when AnisotropicFiltering\AntiAliasing is on in some games text and interface blurry
![screenshot0000](https://user-images.githubusercontent.com/21084600/165486350-f17bdedb-63a9-42ba-81d0-70cab8565920.png)
Space Rangers 2. If disable AnisotropicFiltering and AntiAliasing:
![screenshot0001](https://user-images.githubusercontent.com/21084600/165487360-e7dd2b2a-a50d-45b9-95fc-4a3d4511a8fd.png)
same feature have dgVoodoo, but he unsupported this game. DxWrapper good work with ddraw.dll and D3D9.dll and option FullscreenWindowMode (Dd7to9\EnableD3d9Wrapper).

**Comment by Mitradis** [comment]
Can someone tell me where to add such a check to the code?

**Comment by elishacloud** [comment]
> Need for AntiAliasing too. Becouse AntiAliasing also causes blur.

There is probably not much that can be done about AntiAliasing.  That is the way it works.

**Comment by Mitradis** [comment]
it's a pity. But at least it succeeded with AF!

**Comment by elishacloud** [comment]
I could try turning off AntiAliasing when using point filtering and then turning it back on when using other types of filtering.  Not sure it this will work.  I'll make a build at some point and have you test it.

**Comment by Mitradis** [comment]
thank! of course I will test.

**Comment by elishacloud** [comment]
I won't have time for a while, but you can try changing the function code [here](https://github.com/elishacloud/dxwrapper/blob/6be80570acfcfd2b6f8e0aec1ed250dd96f5be5c/d3d9/IDirect3DDevice9Ex.cpp#L1309-L1335) to this:

```c++
HRESULT m_IDirect3DDevice9Ex::SetSamplerState(THIS_ DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD Value)
{
	Logging::LogDebug() << __FUNCTION__ << " (" << this << ")";

	// Disable AntiAliasing when using point filtering
	if (Config.AntiAliasing)
	{
		if (Type == D3DSAMP_MAGFILTER || Type == D3DSAMP_MINFILTER || Type == D3DSAMP_MIPFILTER)
		{
			if (Value == D3DTEXF_NONE || Value == D3DTEXF_POINT)
			{
				SetRenderState(D3DRS_MULTISAMPLEANTIALIAS, FALSE);
			}
			else
			{
				SetRenderState(D3DRS_MULTISAMPLEANTIALIAS, TRUE);
			}
		}
	}

	// Enable Anisotropic Filtering
	if (MaxAnisotropy)
	{
		if (Type == D3DSAMP_MAXANISOTROPY)
		{
			if (SUCCEEDED(ProxyInterface->SetSamplerState(Sampler, D3DSAMP_MAXANISOTROPY, MaxAnisotropy)))
			{
				return D3D_OK;
			}
		}
		else if (Type == D3DSAMP_MAGFILTER || Type == D3DSAMP_MINFILTER)
		{
			ProxyInterface->SetSamplerState(Sampler, D3DSAMP_MAXANISOTROPY, MaxAnisotropy);

			if (Value == D3DTEXF_LINEAR)
			{
				Value = D3DTEXF_ANISOTROPIC;
			}
		}
	}

	return ProxyInterface->SetSamplerState(Sampler, Type, Value);
}
```

If you can test this let me know the results.

**Comment by Mitradis** [comment]
Yes! It work! Now AF and AA work together:
![screenshot0000](https://user-images.githubusercontent.com/21084600/165600751-c83ca97b-151a-4e37-87b7-8031a4047f73.png)
![screenshot0001](https://user-images.githubusercontent.com/21084600/165600757-8cb4c228-f215-452e-88cb-0d55cc69bbab.png)
![screenshot0002](https://user-images.githubusercontent.com/21084600/165600763-eb93c170-87f3-4c59-a612-c293bd1e6949.png)
Thanks a lot!

**Comment by elishacloud** [comment]
Thanks for testing this for me.  I have updated the code for all future releases.

**Comment by Mitradis** [comment]
I still suggest making this optional, through the settings. it's probably not necessary for everyone games.

**Comment by elishacloud** [comment]
I actually don't see much need on any game of having Anisotropic or AntiAliasing on when using point or no filtering.  The only potential issue would be if a game uses point or no filtering at one stage and then linear at another stage.  This would confuse my code so that it could disable AntiAliasing in some places it should not.  However, I don't think that will be very common.  I will add an option later if this becomes an issue with any game.

**Comment by Mitradis** [comment]
I deleted previous post for a reason. I tested on 18 games this. I tested it the same way in dgVoodoo. I came to the conclusion that this feature (Keep Filter) should be enabled by default for all games and any situation. I noticed damage (blurry) elements (textures or interface\text), if used AF for all, in various games and even where I have not associated it with this before (e.g. blurry texture building block in warcraft3).

**Comment by Mitradis** [comment]
@elishacloud  On latest build planet battles runs in windows mode, not in fullscreen mode. If set FullScreen = 1 planet battle not start (the loading screen freezes and the mouse too). Can you check?

**Comment by elishacloud** [comment]
Yes, `FullScreen` is probably not a good option for this.  That option is for games that aren't using supported version of DirectX or are using GDI.  For games using supported versions of DirectX, like this game, I recommend that you use `FullscreenWindowMode`.

Note: I see the same issue with a couple other games such as: Deus Ex, Konung 1 & 2, Knight Rider 2 and Unreal Gold

I have this issue on my list to look it.  It is kind of complicated because Direct3D9 handles setting the GUI and screen resolution very different from how it was done in DirectDraw (which is what this game uses).  Let me know what the results of using `FullscreenWindowMode` is for this game.

**Comment by elishacloud** [comment]
BTW: I am assuming it is a DirectDraw game because you had `Dd7to9` set.  However, since I see you also have `EnableD3d9Wrapper` set that could be wrong.  If this is a Direct3D9 game then I recommend that you disable `Dd7to9` and `EnableDdrawWrapper` and just use `EnableD3d9Wrapper`.

If this is a DirectDraw game then I recommend you disable EnableDdrawWrapper` and `EnableD3d9Wrapper` and just use `Dd7to9`.

**Comment by Mitradis** [comment]
this game use d3d9.dll and ddraw.dll together. ddraw.dll for space and d3d9.dll in planet battles.

**Comment by elishacloud** [comment]
> this game use d3d9.dll and ddraw.dll together. ddraw.dll for space and d3d9.dll in planet battles.

I see.  Technically I don't really support this case.  My `Dd7to9` feature converts the code to Direct3D9.  If the game already uses Direct3D9 then they could conflict with each other.  I had some hack in the past to try and get this use case to work, but I removed it because it caused more issues than it solved.

I guess if you just enable `EnableD3d9Wrapper` the game will work correctly.  Otherwise, you could try just enabling `FullscreenWindowMode` instead to just fix the windowed mode issue.

**Comment by Mitradis** [comment]
without ddraw.dll and EnableDdrawWrapper game not started. ddraw is main for this game.

**Comment by elishacloud** [comment]
Enabling both `EnableDdrawWrapper` and `EnableD3d9Wrapper` should be fine.  Those just wrap the DirectDraw and Direct3D9.  Are you still seeing an issue if you just enable those two and disable `dd7to9`?

**Comment by Mitradis** [comment]
Once again:
for start game need d3d9.dll and ddraw.dll and Dd7to9=1. With this game work but planet battles runs in window mode. If set FullScreen=1 loading screen freezes and help only task manager. Thats all.

**Comment by Mitradis** [comment]
And iam talking about original game "space rangers 2 reboot" from 2007.

**Comment by elishacloud** [comment]
Did you ever try with `FullscreenWindowMode` instead of `FullScreen`?

**Comment by Mitradis** [comment]
Oh sorry. Now fine.
