### ISSUE TITLE
Blood 2 - high resolution fix

### ISSUE THREAD

**Issue by Keith94** [elishacloud/dxwrapper#15]
In case it is interesting to you, there's a high resolution fix available here - http://dege.freeweb.hu/Patches/Patches.html

>This one fixes the crash that occurs when a resolution with more than 1000 lines is tried to be used.

**Comment by elishacloud** [comment]
Yes, I did see that.  There is also a full fix page [here](https://steamcommunity.com/app/299050/discussions/0/405692758722194702/) to explain how to get the game working on Windows 10 with the high resolution patch.

However this patch requires replacing some of the original Blood 2 files.  It also distributes exe files in the patch.  Those are two things I try to avoid.  With my fixes I want to get the game running without replacing any of the original game files.  I personally don't like replacing the original exe file (or any other file in a game) because it is hard to know which exe files on the Internet you can trust.  Note: how even my no-CD fixes don't require replacing any files (check out this page [here](https://github.com/elishacloud/dxwrapper/wiki/Diablo#no-cd-patch) and [here](https://github.com/elishacloud/dxwrapper/wiki/WarGames#no-cd-patch)).

Also as a side note it seems like the fix requires [dgVoodoo2](http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2.html).  dgVoodoo2 is a great tool and there are several games I have not yet got working without it.  However I prefer **not** using it when possible since there is no open source version and it seems like the configuration is global as opposed to game-specific.

If you want to use the high resolution fix you can simply disable the resolution limiter in DxWnd in my fix.  I might update the wiki with details on this later.  I might even create my own high resolution fix that does not require replacing any exe files.  :-)

**Comment by Keith94** [comment]
Yeah, I figured you didn't want to include that replacement exe for a reason. :) But if you can patch it your own way that would be more interesting. I guess it's a renderer/engine problem?

**Comment by mirh** [comment]
> This one fixes the crash that occurs when a resolution with more than 1000 lines is tried to be used.

Remembers me of how Direct3D 6 maximum supported dimensions size is 2048 afaik (in fact dgVoodoo2 is the recommended fix for such case in Omikron: The Nomad Soul)
Not sure about blood.

**Comment by elishacloud** [comment]
Here is an update for dxwrapper that works with Blood 2.  This update supports the [high resolution fix](http://dege.freeweb.hu/Patches/Patches.html) by Dege so that you can play the game at 4k resolution.

Download the update from here: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/2872503/dxwrapper.zip)

**Comment by Keith94** [comment]
So, does it make sense to remove the DxWnd Limit Resolution fix?

**Comment by elishacloud** [comment]
Completely removing the DxWnd files may be the best solution here.  I was able to get it to run once on resolution higher than 2048 width.  But was not consistent.  I also had to either enable DDrawCompat Experimental or set Windows XP SP2 compatibility mode.

**Comment by Keith94** [comment]
Thanks. And this wrapper also fixes the performance issues, I assume? Haven't had time to test it yet.

**Comment by elishacloud** [comment]
Yes, the DDrawCompat option is able to fix the performance issues.

**Comment by Keith94** [comment]
I think this is resolved.
