### ISSUE TITLE
CD Check on Diablo isn't disabled by fix

### ISSUE THREAD

**Issue by blam666** [elishacloud/dxwrapper#16]
I tried the method provided here and copied ddraw.dll and ddraw.ini of your fix to my D:/GAMES\Diablo game folder, as well as the DIABDAT.MPQ file from the cd. But it still asks for the CD.

I'm using Diablo 1.0 retail CD, Windows 10 64. It works with the iso enabled in Drive E:\

Am I missing something? No compatibility setting changed anything about the CD check.

Hope u can help, as I'm out of ideas...

**Comment by Keith94** [comment]
Patch the game to 1.09 or 1.10, I think.

**Comment by blam666** [comment]
Ah, true it's still 1.0. Will try upgrading, thx for the tip.




Am 26.02.2018 20:06 schrieb "Keith94" <notifications@github.com>:

Patch the game to 1.09 or 1.10, I think.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/elishacloud/dxwrapper/issues/16#issuecomment-368612709>,
or mute the thread

**Comment by elishacloud** [comment]
1. @Keith94 is correct.  It needs to be on the latest version which is v1.09.
2. Some systems won't load ddraw.dll from the game folder and you need to rename both files to dsound.dll and dsound.ini.  I saw this on Windows 7.  You are using Windows 10 so you should be ok using ddraw.dll, but this is something you can try is the first item does not help.
3. If you still have problems after these two items then please attach your log file.

**Comment by blam666** [comment]
Ok, thanks a lot to both of you. Patched on 1.9 and it worked fine now without the cd, exactly as you said.

I got the hint from PCGAMINGWIKI and there weren't any infos about the patch not working on 1.0, so I was a bit confused. 

I'm a little bit bothered that another info on PCGAMINGWIKI was unfortunately correct: there is no music on character creation screen. I will see if there are other things bothering me more with the 1.0 and decide which version to play then, if I will just use auto-iso load with 1.0 or play without cd on 1.9 in the future.

**Comment by mirh** [comment]
If you don't feel like fixing info yourself, tell some of the dudes here https://discord.gg/UU9e7u

**Comment by Keith94** [comment]
>I got the hint from PCGAMINGWIKI and there weren't any infos about the patch not working on 1.0, so I was a bit confused.

True, I forgot to include that bit when writing the instructions. Guess I'll add it.

**Comment by elishacloud** [comment]
You can use DxWrapper to automatically load the Diablo ISO when the game starts and then automatically unload the ISO when the game exits.  This will work on any version of Diablo.  I created a batch file below to do that.

Here are the steps:
1. Unzip the following batch file below into your Diablo game folder: [LoadIso.zip](https://github.com/elishacloud/dxwrapper/files/1764281/LoadIso.zip)
2. Modify the following two lines in the dxwrapper ini file (`ddraw.ini`):
``` text
RunProcess               = LoadIso.bat
WaitForProcess           = 1
```
3. Copy the Diablo ISO into the Diablo folder and rename it to `Diablo.iso`
4. Play the game and enjoy.

Note: this will add a short delay to the game launch while it is loading the ISO.  This can be done with any game ISO by simply modifying the first two lines of the batch file.  This only works on Windows 8 and above.

I am closing this issue since it looks like the original issue is resolved.

**Comment by Keith94** [comment]
You are full of solutions. ;) Thanks for sharing Elisha.
