### ISSUE TITLE
Is there a way to get DXWrapper to run on GFWL titles?

### ISSUE THREAD

**Issue by Laksh2007** [elishacloud/dxwrapper#202]
I'm just curious but is there actually a way to get DXWrapper to run on GFWL titles? If you find this post a time waste that's fine you can just close it.

**Comment by elishacloud** [comment]
I looked at the list of GFWL games.  I know some of the games on that list will work with dxwrapper.  However, I never tested the GFWL version of the games.  For example, I know that Age of Empires works with dxwrapper.  But I only tested the CD and trial versions of the game.

If the GFWL games use DirectX 1-9 then they should work with dxwrapper.

**Comment by Laksh2007** [comment]
I tried Fallout 3, GTA IV, Flatout Ultimate Carnage. None of them worked unless I disable GFWL.

**Comment by Ston3Cold** [comment]
> I tried Fallout 3, GTA IV, Flatout Ultimate Carnage. None of them worked unless I disable GFWL.

It's because GFWL does a file integrity check regarding files in the directory. If it detects anything other than the files the game installed with, it will not work / crash / boot or cause issues. Have witnessed this myself with Section 8 and Section 8 Prejudice.

**Comment by mirh** [comment]
A file integrity check against what?
Dxwrapper doesn't replace any game file.

**Comment by elishacloud** [comment]
It is possible that GFWL games check the certificate of each dll loaded.  That is one reason I made dxwrapper's stub be able to load dxwrapper into memory (rather than as a file).  If the stub was signed then it can load into games that validate the signature and it can load dxwrapper into memory even without it having a signature.  That way only a single stub file would need to be signed once.  Then you could use that signed stub to load any version of dxwrapper.

I know that some Steam games check digital signatures, but I am not sure if that is the case with GFWL games.  Also, I don't have a signed copy of the dxwrapper's stub to test with.

**Comment by mirh** [comment]
Did XP already have authenticode? Because otherwise it seems strange.
(conversely it seems impossible that the average game developer remembered to sign all its dlls, but those might have a whitelist)

**Comment by elishacloud** [comment]
Either case, there should be a way to get dxwrapper working with GFWL titles, as long as they use DX 1 to 9.

**Comment by elishacloud** [comment]
Closing this as not planned.
