### ISSUE TITLE
Arx Fatalis does not boot.

### ISSUE THREAD

**Issue by Speedwagen** [elishacloud/dxwrapper#205]
I just tried to run the DirectX 7 Wrapper provided by Kim. 
Here is the log for Arx Fatalis.
[dxwrapper-arx.log](https://github.com/elishacloud/dxwrapper/files/11800209/dxwrapper-arx.log)
The game does not boot.

**Comment by elishacloud** [comment]
I got the game to boot with the latest update I just checked in.  However, this game uses `SetRenderTarget()` which I have not implemented properly yet.  Also, it uses FOURCC surface formats that have no been implemented yet.

**Comment by Speedwagen** [comment]
Does this render some objects invisible?

**Comment by Speedwagen** [comment]
Quick question, where are you seeing the rendertarget?

**Comment by Speedwagen** [comment]
im trying to determine the render targets for my rtx remix projects. I will try those functions now

**Comment by Speedwagen** [comment]
after enabling `EnableDdrawWrapper` and `DDrawCompat` I had this in my log.

**Comment by elishacloud** [comment]
> im trying to determine the render targets for my rtx remix projects.

If you are trying to use RTX Remix then you will need to enable `Dd7to9` in the ini file, as RTX Remix only supports Direct3D9 and you need this setting in dxwrapper to convert the game to Direct3D9.  You can disable the other settings, as only `Dd7to9` is needed in this case.

However, as I mentioned before the SetRenderTarget() code in dxwrapper is not fully implemented so it is not able to fully convert all of this game to Direct3D9.  If you remark out [these lines](https://github.com/elishacloud/dxwrapper/blob/fa3357f38dc1176aad05767952d11c773048f25b/ddraw/IDirect3DDeviceX.cpp#L917-L923) and recompile the code then you can get the game to load up.  However, it will have issues because remarking those lines out just disables SetRenderTarget(), which is required by this game.

**Comment by Speedwagen** [comment]
Ahh I see! I am using a specific version of Arx Libertatis to use for RTX remix but have been running into a problem where the interactable objects do not render. RTX remix currently only points to render target 0 so I was trying to find out which other render targets the application points to.
And because of this tried to explore other potential paths such as DXWrapper to have it wrap to DirectX 9 and just maybe solve the issue.

**Comment by elishacloud** [comment]
As far as I know, DirectX 7 games (like Arx Fatalis) only use render target 0.

For Arx Libertatis, I am not sure what the solution is.  Dxwrapper has a DirectX 9 wrapper, but it is not able to convert all the render targets to 0.  It seems like it would take a lot of effort to covert a game from using multiple render targets to using only one.

You could use dxwrapper to log which Direct3D 9 render targets are used by adding some logging [here](https://github.com/elishacloud/dxwrapper/blob/fa3357f38dc1176aad05767952d11c773048f25b/d3d9/IDirect3DDevice9Ex.cpp#L521-L531).  Just enable the `EnableD3d9Wrapper` option in the ini file for DirectX 9 games.

**Comment by elishacloud** [comment]
I put an update in that allows Arx Fatalis to run without any code changes.  It is still not playable as it has corrupt graphics on the main menu, at least it can start now.

**Comment by Speedwagen** [comment]
Oh, amazing. Thanks, I will try it when I get home tonight.

**Comment by elishacloud** [comment]
With the latest build if you enable the below settings the game is getting close to being playable, but still has a lot of graphical anomalies.

```ini
[Compatibility]
Dd7to9                     = 1

[d3d9]
FullscreenWindowMode       = 1
```

**Comment by Speedwagen** [comment]
wow, that is awesome. I have not had a chance to run this yet but will test as soon as I can.

**Comment by Speedwagen** [comment]
Hi there. I just wanted to apologise as I have not had a chance to actually take a look at the changes for this.
I will actually have a look at this tonight.

**Comment by elishacloud** [comment]
No problem.  Here is the latest build to test with.  The game is still not playable, but it is further along.

Here is the test build:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12314674/dxwrapper.zip)

**Comment by elishacloud** [comment]
The game is mostly playable with the latest build if you do the following:

1. Disable in-game Bump Mapping and Rendering Fix
2. Enable `Dd7to9` and `FullscreenWindowMode` in dxwrapper

Here is the latest build:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12611252/dxwrapper.zip)

**Comment by Speedwagen** [comment]
[dxwrapper-arx.log](https://github.com/elishacloud/dxwrapper/files/13164142/dxwrapper-arx.log)
Hi, I tried to run the application with the recommended but the application would not load. I have attached the log file for you to peruse.

**Comment by elishacloud** [comment]
@Speedwagen, that is an old build.  I never updated this thread with the latest build.  However, I put a lot of fixes in since then.

The [released](https://github.com/elishacloud/dxwrapper/releases) build should work for you.  Make sure you disable both the in-game options:  Bump Mapping and Rendering Fix.  You also need to enable `Dd7to9` and `FullscreenWindowMode` in dxwrapper.

Note: I am using the GOG version of the game.  Not sure if other versions work the same as the GOG version.

Also, make sure you disable all compatibility settings:

![image](https://github.com/elishacloud/dxwrapper/assets/25625456/64096ed7-0e19-4c37-b2cf-c9d43ccefecb)

**Comment by Speedwagen** [comment]
I think I got it to boot. Switched to software mode and the display looks like this haha.
![parsecd_ebcamlJqsw](https://github.com/elishacloud/dxwrapper/assets/110987088/f6303dd1-a0df-464c-8676-f7c1c3dcc0d6)
[dxwrapper-arx.log](https://github.com/elishacloud/dxwrapper/files/13174769/dxwrapper-arx.log)

**Comment by elishacloud** [comment]
I got most of this game to run in Direct3D mode.  There are still some lighting issues, but it seems to work other than that.  Here is the updated build:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/14625851/dxwrapper.zip)

**Comment by elishacloud** [comment]
I fixed the color key issues.  This build has almost all the issues fixed:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/15287977/dxwrapper.zip)

**Comment by elishacloud** [comment]
This latest build should fix all issues with this game.  The only thing remaining is that the character creation screen still runs a bit slow.  But everything else should be working;

Here is the build:  [dxwrapper.zip](https://github.com/user-attachments/files/16318099/dxwrapper.zip)

**Comment by elishacloud** [comment]
This issue is fixed in the latest release.  Arx Fatalis is fully supported.
