### ISSUE TITLE
Metal Gear Solid 1 - Bugged FMV

### ISSUE THREAD

**Issue by Tomasak** [elishacloud/dxwrapper#22]
Not sure if this any related the DirectX or something, but the FMV doesnt show up correctly, only sound can be heard. Supposedly it only works on W98.
![metal gear solid mgsi exe screenshot 2018 05 18 - 11 23 13 65](https://user-images.githubusercontent.com/11007651/40227203-1e8f0674-5a8e-11e8-8eec-c79fab870eb0.png)

**Comment by maximilien-noal** [comment]
It can work on Windows XP, but it depends on the hardware.

Desktop PC with Intel Pentium III @ 800 MHz + GeForce 4 Ti 4800 ? Yes.
Laptop PC (IBM Thinkpad T43) with Intel Pentium M CPU @ 1.8 GHz + ATI Radeon Mobility X300 ? No.

**Comment by Tomasak** [comment]
I tried quartz.dll from MGS2 green screen issue thread and it doesnt help here sadly :/.

**Comment by mirh** [comment]
> but it seemingly depends on the hardware

~~Could it be it requires some codec that only nvidia manages to revive?~~

**Comment by maximilien-noal** [comment]
It's not a matter of codec I don't think, as it doesn't use WinMM, VfW, DirectShow, or some such API.

**Comment by elishacloud** [comment]
I cannot properly test the game since it tells me that I need to "Insert DISC 1".  However, I was able to get the intro videos to play with this update.  Try this update and let me know the results.

Here is the update: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/3965657/dxwrapper.zip)

_Note: this sets the resolution to 640x480, which is the highest natively supported by the game.  If you have a hi-res patch installed you will need to configure the included ini file for the new resolution._

**Comment by Tomasak** [comment]
Intro videos always appeared without problem. Issue is that real life footages does not appear.
You can test em via Extra -> previous operations -> roll a and skipping until you get to cutscene with revolver ocelot.
[SavedGames.zip](https://github.com/elishacloud/dxwrapper/files/3978350/SavedGames.zip)
Also iirc if you play game in HW mode, game supports up to 800x600 or even 1024x768, but i cant get that to work with your wrapper or without any.

**Comment by elishacloud** [comment]
> You can test em via Extra -> previous operations -> roll a and skipping until you get to cutscene with revolver ocelot.

Ok, let me take a look at that.

> Also iirc if you play game in HW mode, game supports up to 800x600 or even 1024x768, but i cant get that to work with your wrapper or without any.

Yes, this is because I am using DirectDraw conversion to DirectX9.  However, for hardware to work I need to convert Direct3D to DirectX9, which I have not created yet.  I guess this is at least a year away.  However, maybe I can get it working without converting the game to DirectX9.

**Comment by elishacloud** [comment]
@Tomasak, try with my latest release.  This converts DirectDraw to DirectX9 and should fix the issues with this game.  Just unzip this into the game's folder overwriting any files.

Here is the update:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/5092321/dxwrapper.zip)

**Comment by Tomasak** [comment]
Sadly this only crashes for me, even software mode to which game should boot after first crash. Log here, if it's any helpful
[dxwrapper-mgsi.log](https://github.com/elishacloud/dxwrapper/files/5097693/dxwrapper-mgsi.log)

**Comment by Tomasak** [comment]
![Metal Gear Solid(mgsi exe) Screenshot 2020 09 25 - 18 13 49 45](https://user-images.githubusercontent.com/11007651/94290814-ffaeb280-ff5a-11ea-82df-846cd44168b5.png)
GOG version has it fixed :)

**Comment by elishacloud** [comment]
Ok, that's great!  Thanks for sharing!

**Comment by mirh** [comment]
> well i noticed in log that resolution 320xsomething was not found,

What if you add it (320x240?) with CRU?

**Comment by elishacloud** [comment]
> What if you add it (320x240?) with CRU?

Yes, I recently added support for 320x240:  [here](https://github.com/elishacloud/dxwrapper/blob/7febf176fdcd98c593c5dec819785452f58cbb8f/ddraw/IDirectDrawX.cpp#L1355-L1362) and [here](https://github.com/elishacloud/dxwrapper/blob/7febf176fdcd98c593c5dec819785452f58cbb8f/ddraw/IDirectDrawX.cpp#L2240-L2248)

**Comment by elishacloud** [comment]
> You can test em via Extra -> previous operations -> roll a and skipping until you get to cutscene with revolver ocelot.

I don't have a "roll a" under Extra -> Previous Operations.  It could be because I have the demo version.  However, I did notice an issue.  It appears that the FMVs are playing at 320x240, which is not supported on newer operating systems.  I just added support for that resolution so you could try my latest update and see if that works.

Here is my latest build:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/5287652/dxwrapper.zip)

**Comment by Tomasak** [comment]
Game now launches, but FMVs are still broken
(and damn, playing in software, polygons wobble like on PS1 :D )

**Comment by elishacloud** [comment]
Thanks for testing.  Yeah, this is going to play in software until I get the 3D (hardware) API conversion finished.

**Comment by elishacloud** [comment]
The FMV's should be fixed with the GOG version and the latest [release](https://github.com/elishacloud/dxwrapper/releases) of dxwrapper supports this game fully.

Closing this now.  You can reopen it if there is still an issue.

**Comment by billbeans** [comment]
Is there a way to actually render them on the old retail release though? I'm not understanding why it's so hard for this game when original Abe's Odysee seems to work fine.

**Comment by elishacloud** [comment]
@billbeans, The original PC release of Metal Gear Solid 1 shipped with the DDV playback components from Digital Dialect.  These videos are playing using proprietary playback software.  As far as Abe's Odysee, it just blt's the videos to screen, so no issues.

The best solution is to do one of these options:

1. Install the latest official patch for the PC version
2. Use the GOG release

_Note: I only have the GOG version so I cannot check anything else._

**Comment by billbeans** [comment]
Is the playback software compiled into the game exes? Because I don't see any kind of alternate video player in my install dir. I would try converting the files to avi and see what happens, but even that is proving to be difficult. I'm much more interested in getting the original game disc to work. Everything else works great, but not these FMVs. Usually Wine is pretty good with old software like this.

If you feel like looking at it, I can send you the original disc images. You don't need a cracked executable, despite what others above have said. You can just mount the disc you want to play in Daemon Tools or similar and put the version.dll [from this repo](https://github.com/nckstwrt/SafeDiscLoader2) in your game dir, at least that worked for me.

I also used the [MGSI Launcher](https://mgs.w00ty.com/mgs1/launcher/) to install game-fixing patches, except for the widescreen mod which I couldn't get working. I don't think there's an official patch.

Also found [this](https://github.com/maximilien-noal/MGSLauncher) which attempts to fix the ddv issue.

**Comment by mirh** [comment]
https://www.vogons.org/viewtopic.php?t=56659

**Comment by billbeans** [comment]
> https://www.vogons.org/viewtopic.php?t=56659

Yep, I actually linked that guy's repo in the final sentence of my previous comment. Unfortunately it requires you to convert the ddv videos to wmv for it to work, and I still can't find any software that can convert those files. I found a YouTube video of all the fmvs, which I could easily split and convert to wmv, but I'm unsure which files are which clip so I don't know what to name them.

In these past few hours, I even went so far as to install Windows 98 on 86Box just to see if what would happen, but the game wouldn't even start. I may have done something wrong though, I don't see how emulation wouldn't be enough.

Also I did try the GOG release, and the videos and audio were super choppy for me, I don't know if they're supposed to be that way. So even the GOG's not great, unless it's just me.

**Comment by billbeans** [comment]
Well I did finally get the original game running in Win98 under 86Box, but only in hardware mode. Had to use the Voodoo3 display and install drivers for it. The FMVs play perfectly this way - smooth 30 frames, no audio issues. So we know it's possible.
