### ISSUE TITLE
How do I set it up to better support the old Legend of Mir3 , please help me!

### ISSUE THREAD

**Issue by Leewx820** [elishacloud/dxwrapper#241]
![ScreenShot1](https://github.com/elishacloud/dxwrapper/assets/26474036/da279706-3a44-4290-a70a-f0943ce83ab3)
![ScreenShot2](https://github.com/elishacloud/dxwrapper/assets/26474036/f600adb1-40df-4c6a-a9a4-c6d3d3d6ae8a)

I've been playing old Legend of Mir3, but it doesn't work on newer systems, I found dxwrapper and tried it, but it still doesn't work, how do I set it up so I can play the game properly, as far as I know the game uses directdraw.

**Comment by Leewx820** [comment]
I can provide the full program.

**Comment by elishacloud** [comment]
Are the screenshots with or without dxwrapper?  What settings are you using for this?  Can you send me the log file?

**Comment by elishacloud** [comment]
Yes.  This is a Direct3D game.  The support for Direct3D is still limited.  Dd7to9 tries to convert the game to Direct3D9.  This issue here has to do with the game trying to modify the backbuffer or the primary surface directly, which is not normally allowed in newer versions of DX.  There is a potential fix, but its not too easy and I am afraid it will cause the game to run slow.

One idea, I noticed you are playing this on VMware.  If you can try playing this on Windows 7/10/11, non-VMware then you could try using DDrawCompat.  But that only works on a non-VM machine.

**Comment by elishacloud** [comment]
Did you try using DDrawCompat on a physical machine?

**Comment by Leewx820** [comment]
I realized that I was using high dpi, I disabled high dpi and it worked fine.
![image](https://github.com/elishacloud/dxwrapper/assets/26474036/c22468a6-dd85-4e2b-9e73-280722abc19e)

**Comment by elishacloud** [comment]
Very good.  How did you disable High DPI?  In Windows?  In the compatibility settings for this game?  Which option did you chose?

I don't have this game so I cannot test it.
