### ISSUE TITLE
D3D9 reading internal fields of resources?

### ISSUE THREAD

**Issue by CookiePLMonster** [elishacloud/dxwrapper#27]
Notice this is not about dxwrapper at all, more about a weird discovery I just had with a D3D9 wrapper (which might affect yours too).

Take a look at this crash:

![image](https://user-images.githubusercontent.com/7947461/42476964-e454d02c-83cf-11e8-8489-0388d6dab7cb.png)

And this code it crashed at:

![image](https://user-images.githubusercontent.com/7947461/42477003-fca4621e-83cf-11e8-97ef-b5efe3144cd3.png)

Why has this never been a problem? Looks like D3D9 reads an internal field of this D3D9 vertex buffer here!

**Comment by CookiePLMonster** [comment]
Of course, passing a "real" interface to `SetStreamSource` instead of a wrapper helped - but is it me just being dumb and forgetting something or something wrappers didn't account for so far?

**Comment by elishacloud** [comment]
I am not exactly sure which quirk you are asking about.  I have found several different issues with wrapping DirectX APIs.  I was hoping to write up a wiki to discuss each of them in more detail, but never got around to it.

The crash happens at that location, but the issue could have been a ways up the stack.  The problem with wrappers is that if you don't wrap everything correctly then it is possible for the process to get the actual d3d9 interface rather than your wrapper interface.  This can cause all kinds of issues.  In one game I saw a case where the real interface was exposed at the beginning of the game but it did not crash until you left the game or started a new match, which could be hours later.

Actually in d3d9 I believe you have a chance of crashing, depending on what the game does, if you don't wrap **every** interface.  I believe every interface in d3d9 has at least one function where you need to swap the address with the wrapper address.

For the VertexBuffer there is function called [`GetDevice`](https://github.com/elishacloud/DirectX-Wrappers/blob/9ba5e5d7eb9d8f8759b49a008df5e8a5c7a11fb2/d3d9/IDirect3DVertexBuffer9.cpp#L43).  For Textures there is a function called [`GetSurfaceLevel`](https://github.com/elishacloud/DirectX-Wrappers/blob/9ba5e5d7eb9d8f8759b49a008df5e8a5c7a11fb2/d3d9/IDirect3DTexture9.cpp#L137). Etc...

I am not sure if this is useful or not.  Let me know if you need any specific data.  You are always welcome to use my wrappers.  I spent a good amount of time trying to make sure they can fully wrap all interfaces.  It is strictly a wrapper with no additional code in it.

**Comment by CookiePLMonster** [comment]
What I haven't noticed at the moment of creating this issue is what in any function passing resources to the device (like `SetStreamSource`) you are passing underlying resources instead of the wrapper itself. On the second thought it makes sense, since D3D has a right to internally assume those resources are "final" and thus refer to them directly and not via virtual methods.

**Comment by elishacloud** [comment]
Yes, you need to pass the real resource to D3D and the wrapper interface to the game process.  If you check out my [DirectX-Wrappers](https://github.com/elishacloud/DirectX-Wrappers) project and look at the [d3d9 wrapper](https://github.com/elishacloud/DirectX-Wrappers/tree/master/d3d9) you can see which functions I pass either the real or the wrapper interface.

If the function just has a `return ProxyInterface->(function_name)` then you don't need to do anything to that function.  Example: [https://github.com/elishacloud/DirectX-Wrappers/blob/master/d3d9/IDirect3D9Ex.cpp#L57](https://github.com/elishacloud/DirectX-Wrappers/blob/master/d3d9/IDirect3D9Ex.cpp#L57)

For other functions there will be additional code to either do one of these three things:
1. Lookup the [wrapper address](https://github.com/elishacloud/DirectX-Wrappers/blob/master/d3d9/IDirect3DDevice9.cpp#L85).
2. Create a [new wrapper interface](https://github.com/elishacloud/DirectX-Wrappers/blob/master/d3d9/IDirect3D9Ex.cpp#L121).
3. Lookup the [resource address](https://github.com/elishacloud/DirectX-Wrappers/blob/master/d3d9/IDirect3DDevice9.cpp#L250).

I should also mention that when I lookup the wrapper address [if it does not exist then I create a new interface](https://github.com/elishacloud/DirectX-Wrappers/blob/master/Common/Wrapper.h#L35).

**Comment by CookiePLMonster** [comment]
Cool! So it was purely an oversight on my part and not some thing everyone forgot about... good to know!
