### ISSUE TITLE
Update Configuration Wiki

### ISSUE THREAD

**Issue by AndhikaWB** [elishacloud/dxwrapper#40]
The current [configuration wiki](https://github.com/elishacloud/dxwrapper/wiki/Configuration) provided is not complete and/or outdated. It causes confusion to me and probably many other people. Could you update it at least 1 by 1 when you have free time?

**Comment by elishacloud** [comment]
Thanks for your comments!  I am pretty bad at keeping my documentation up-to-date.  But I will try and update it soon.  Thanks.

**Comment by AndhikaWB** [comment]
Thank you, and I'm also confused about the _stub.ini_ file. For example, I already copied _dxwrapper.dll_, _dxwrapper.ini_, and _d3d9.dll_ to my game dir. Do I need to rename stub.ini to d3d9.ini first? Is it really required to copy it to my game dir too since I already have the _dxwrapper.ini_ file?

**Comment by AndhikaWB** [comment]
Some description could also be improved a bit to minimalize confusion in my opinion.

For example, you said on `LoadCustomDllPath` that 

> you can specify just the dll name ...

so should I write it as _mycustomdllname_ (without extension) or _mycustomdllname.dll_? Well.. I'm not actually confused with this one, but other people may.

**Comment by elishacloud** [comment]
For most cases you don't need the stub.ini file.  The main case you need to use that is if you want to wrap a custom dll.  For example, if you are using a GOG game and the game already comes with a ddraw.dll file.  In that case you could do the following:

1. Rename the GOG ddraw.dll file to ddraw-GOG.dll.
2. Copy in the ddraw.dll (stub) and the dxwrapper.dll and dxwrapper.ini files.
3. Add the stub.ini file and rename it to ddraw.ini.
4. Modify the stub config file and change `RealDllPath = AUTO` to `RealDllPath = ddraw-GOG.dll`

This will tell the stub to load ddraw-GOG.dll rather than the System32 ddraw.dll file.

**Comment by elishacloud** [comment]
The [Configuration](https://github.com/elishacloud/dxwrapper/wiki/Configuration) wiki has been updated with all options.  Closing this issue.
