### ISSUE TITLE
Lock Mouse To Screen/Window in Stronghold Crusader

### ISSUE THREAD

**Issue by PodeCaradox** [elishacloud/dxwrapper#67]
Hello,

first of all great Project you do here, it improved Stronghold Crusader Graphic Interface quit well :)

But i have a Problem after enabling Dd7to9 to 1, the Mouse Cursor was Locked on the Game Screen before but after upgrading to the Dd9 it is no more locked what have the issue there is no more Map Scrolling and the mouse go to my Second Monitor.
Here my Settings i use(i know Crusader use DDraw.dll because i saw the import in ida):
[dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/4453508/dxwrapper.zip)

Do you have any idea how i can lock the Mouse to the Stronghold Window, so it wont go to a other Screen, so if anyone have 2/3 Screen Setup no Problems.

Thanks and i hope you have a great day :)

**Comment by elishacloud** [comment]
Hello @PodeCaradox,  I have not added features into the project yet to lock the mouse cursor or features to handle multiple monitors.  However, you could try disabling the `Fullscreen` option.  This might help solve some of the mouse issues.  That option won't work if you have more than one monitor unless you duplicate them instead of extending them.

**Comment by elishacloud** [comment]
I doubt I will get to this anytime soon, if ever.  So I am going to just close it for now.  Closing as not planned.
