### ISSUE TITLE
Gangsters Organized Crime, Main Menu is blacked out

### ISSUE THREAD

**Issue by NateGrett** [elishacloud/dxwrapper#69]
I downloaded your patch, the october 2019 for windows 10 and the game wont show the main menu at all, it goes through the all the starting videos and then nothing, tried running in the compatibility that you showed on the patch page and then some others yet nothing changes

**Comment by elishacloud** [comment]
Yeah, my fix not perfect yet.  The issue with this game is that certain controls (labels, buttons, etc.) will be pushed to the back so they are hidden.  My "fix" simply activates the main window which will reorder the controls so that you can see them.  If the latest release does not work try using an older one.  Maybe one from early 2018 or late 2017.

**Comment by elishacloud** [comment]
I just posted an update patch that should address this issue.  You can see the update here:  [Gangsters Organized Crime patch](https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime)

**Comment by elishacloud** [comment]
This should be fixed with the latest update:  https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime
