### ISSUE TITLE
Gangsters Organized Crime, Menu not rendering correctly

### ISSUE THREAD

**Issue by feuerball11** [elishacloud/dxwrapper#70]
Hi, I'm currently trying to get Gangsters Organized Crime running on Windows 10. 
But with a catch: 
I'm trying to get it run based on the Version on "Computer Bild Spiele" 
I Used your patch but the Main Menu is flickering, sometimes not rendering completely, unless I click on a Button, hold the mouse and drag it outside the button (so I don't actually click it) 

This could be difficult for you to test, as I don't know in which ways the GOG version differs from the CBS Version. Is there a way in which I could assist you, so we can get this issue fixed?

**Comment by elishacloud** [comment]
The issue with this game is that certain controls (labels, buttons, etc.) will be pushed to the back so they are hidden.  My "fix" simply activates the main window which will reorder the controls so that you can see them.  However, each time I reactive the main window it causes all the controls to flash.  So I try to detect when the screen is redrawn and and only active this once when the screen is redrawn.  But I changed this code in one of the latest releases.  Try using an older release and see if that works.

**Comment by elishacloud** [comment]
This issue looks like it is related to issue #69

**Comment by elishacloud** [comment]
I just posted an update patch that should address this issue.  You can see the update here:  [Gangsters Organized Crime patch](https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime)

**Comment by elishacloud** [comment]
This should be fixed with the latest update:  https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime
