### ISSUE TITLE
Knights of Honor

### ISSUE THREAD

**Issue by Mitradis** [elishacloud/dxwrapper#93]
Hi. This game, as a many games on windows 10, have some problems: not detect screen resolution, very fast camera scroll speed, dispensable hight cpu load. But this game react only on 4 dll`s: dsound, msacm32, msvfw32, winmm and not on ddraw.dll. Accordingly [Compatibility] block not work as and other settings except FullScreen = 1. Is it possible to do something better for this good game?

**Comment by elishacloud** [comment]
> But this game react only on 4 dll`s: dsound, msacm32, msvfw32, winmm

dxwrapper supports all of these dlls.  Ideally you would want to use the dll that load soonest in the game because the earlier you can load dxwrapper the better.  You can just rename the `stub.dll` file to any of these dlls.

> and not on ddraw.dll.

It looks like the game is using DirectX 9, which could be why it is not loading `ddraw.dll`.  It is probably loading `d3d9.dll` instead.   However, I don't have a lot of fixes in dxwrapper for this kind of issue with DirectX 9.

You could try setting the `DisableMaxWindowedMode` option.  I just enhanced this option to support DirectX 9

Here is a new update:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/5479373/dxwrapper.zip)

**Comment by Mitradis** [comment]
unfortunately the game does not respond on d3d9.dll, only on dsound, msacm32, msvfw32, winmm.

**Comment by elishacloud** [comment]
That's ok.  Just rename `d3d9.dll` to `dsound.dll`.
